### ISSUE TITLE
Allow user to set their preferred directory to find GEDCOM Files

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#176] opened 2020-06-08 14:44 UTC
**Is your feature request related to a problem? Please describe.**
Indirectly to #175

**Describe the solution you'd like**
File --> Open GEDCOM File defaults to Documents.

Please consider providing a configuration option, perhaps via Tools  --> Options, to allow the user to set a preferred directory to start the Open GEDCOM Files process

**Describe alternatives you've considered**

**Additional context**

**Comment by ShammyLevva** [comment] 2020-09-06 13:58
ie: If something isn't currently saving settings anything such as specifying a directory, will revert to default too. So the issue is getting to the bottom of the lack of saving of settings. This feature already exists but seems it's not working due to not saving issue. I've seen this reported by bugs in the Microsoft Store delivery system. It seems fixed with the release version.

I'll close this issue as the feature already exists but leave the other issue open.

**Closed by ShammyLevva** 2020-09-06 13:58 UTC
