### ISSUE TITLE
Double byte handling bug on Mac version [BUG] 

### ISSUE THREAD

**Issue by tony51** [ShammyLevva/FTAnalyzer#191] opened 2020-11-02 16:26 UTC
**Version Number problem appears in**
Mac V1.3.0 (Build 54)

**Describe the bug**
This app works brilliant in Windows. There is however a glitch when importing a Family Historian ged file into the Mac version. It can take about 2 mins depending on size of file and displays an error message for every line of the gedcom code before giving the results.

**To Reproduce**

![Screenshot 2020-11-02 at 10 32 14](https://user-images.githubusercontent.com/2480648/97890360-5ca14380-1d25-11eb-8b7c-9451c25be25f.png)

[gedcomstats short version.txt](https://github.com/ShammyLevva/FTAnalyzer/files/5476327/gedcomstats.short.version.txt)

**Expected behavior**

**Screenshots**

**Additional context**
The same FH file loads perfectly into FTA in the Win10 version of the app.
I use a MacBook but I can run Win progs in VirtualBox.
I have tried importing a FTM2012 gedcom file into the Mac version which loads fine.

**Comment by ShammyLevva** [comment] 2020-11-02 18:30
Ok that looks like either a compression issue or a text file header issue

The spurious characters at the start looks like it might be suggesting to the app the file is a UNICODE file. When you export from Family Historian on the Mac do you have any "character set" options. If so ideally choose ANSI, or ASCII or possibly if they aren't available one of UTF8/UTF16/UTF32, Avoid UNICODE.

The reason the file looks fine when you view it in a Mac text editor, I am guessing, is that the mac text editor is translating the UNICODE to your installed language. The root cause may be a setting in Family Historian or it may be a language setting in MacOS.

**Comment by ShammyLevva** [comment] 2020-11-02 18:31
You could try emailing me the file to ftanalyzer@gmail.com to see if that looks different to me. In theory the file should open identically on a Mac or Windows as it's just a text file. I'll open in a vanilla text app so I see it's raw details not the tidied up nice details that Mac apps tend to do.

**Comment by ShammyLevva** [comment] 2020-11-02 18:39
Note the 0xA00 (which is the same as 0x0A00) is a new line character so the file starts with a blank link which is fine but the 0x0A00 suggests it's a "double byte" character with the trailing byte being empty 00. Double byte character sets are typically reserved for languages that use a lot of special characters - eg: Chinese/Japanese.

**Comment by ShammyLevva** [comment] 2021-03-08 23:05
Once my new machine arrives (still held up due to world wide lack of NVidia 3080 graphics cards I'll be able to revisit the Mac version and produce a new version based on the latest fixes in the windows version. This bug will be fixed. Meantime the documentation needs to be updated with the example image fix provided.

**Comment by ShammyLevva** [comment] 2023-04-23 22:49
Sadly I no longer have access to a Mac to develop on so the Mac version is mothballed.

**Closed by ShammyLevva** 2023-04-23 22:49 UTC
Labels: bug, Documentation, MAC
