### ISSUE TITLE
International characters issues 

### ISSUE THREAD

**Issue by GeorgesDesilets** [ShammyLevva/FTAnalyzer#48] opened 2018-11-23 02:38 UTC
**Describe the bug**
The location tabs does not recognize french characters anymore since version update 7.0.3.1. This used to work in previous version.
For instance, Montréal, Canada shows up as MontrA©al, Canada

--
To reproduce
![characters issue](https://user-images.githubusercontent.com/45277324/48926767-e4764600-ee9e-11e8-8b9a-6cd7cb474067.jpg)

On Windows 10 running Chrome Browser, import a GEDCOM file from (Ancestry for instance), with french characters.

**Comment by GeorgesDesilets** [comment] 2018-11-24 15:38
Hello Mr Bisset,

Thank you for answer that quickly to my request. I really appreciate you
time and your work.

Here is the link to my hole gedcom file exported from Ancestry yesterday
filed with french canadian ancestors (I am from Montréal, Québec). I am
running version FTAnalyser  7.0.3.1 on Windows 10 with Language and French
Canadian multilingual keyboard settings.

You can see in that this file contains plenty of french characters surnames
and locations with common characters such as é è showing wrong:
BA©cancour,
 instead of Bécancour

Georges Désilets, p. eng
La Prairie, Québec, Canada

Here is the link to the gedcom file
https://drive.google.com/file/d/1imQwLdz9o2ON7c6G-GegkpMgHPkb9T27/view?usp=sharing

**Comment by ShammyLevva** [comment] 2018-11-24 19:59
You can just use notepad. 

There’s a header record then each individual will start with a zero. So just cut n paste the record of individual into a next text file. The header (bit before the first 0 @Inumber@ INDI record

**Comment by GeorgesDesilets** [comment] 2018-11-24 23:18
Hi,
I just realised that simply opening the gedcom file downloaded from
Ancestry in notepad.exe and resaving is enough to fixe the problem in
FTAnalyser. Using diff tool utility, there are no different between the
files, except that the new file is 3 bytes bigger and character set differs
from 'UTF-8' to 'UTF-8 BOM'. See in file diff header below.

[image: image.png]
[image: image.png]

UTF-8 file in FTAnalyser (original from Ancestry)
[image: image.png]

UTF-8 BOM file in FTAnalyser (after open and saved in notepad)
[image: image.png]

Georges Desilets, Montréal, Québec

Le sam. 24 nov. 2018 à 14:59, Alexander Bisset <notifications@github.com> a
écrit :

**Comment by ShammyLevva** [comment] 2018-11-25 09:38
Hmm I wonder what’s going on there. I suspect the change I made to use code page 1252 rather than iso-westerneuropean. I’m on holiday this week so will check when I get back. I suspect the solution is to add an option to let the user select a encoding format to find one that works for them.

**Comment by ShammyLevva** [comment] 2018-11-25 09:41
At the top of the GEDCOM file there will be a line that indicates encoding. Is this what is changing?

**Comment by ShammyLevva** [comment] 2018-11-25 09:43
Btw you could try pasting the images on the Facebook user group. Facebook.com/groups/FTAnalyzer

**Comment by GeorgesDesilets** [comment] 2018-11-25 14:34
The code is in the header is UTF-8

Le dim. 25 nov. 2018 04 h 41, Alexander Bisset <notifications@github.com> a
écrit :

**Comment by amerkasem85** [comment] 2018-12-07 09:48
There is a problem with exported CSV file, it's not support Arabic language 
all exported name encrypted 
thanx

**Comment by ShammyLevva** [comment] 2018-12-08 04:56
Do you have a sample GEDCOM file with Arabic characters in it amerkasem85? I wouldn’t know how to go about creating a test file with them.

**Comment by fire-eggs** [comment] 2018-12-08 19:50
Well, that wasn't much help, was it? FTA imports using Windows-1252 character set, which doesn't have Arabic (or Hebrew) characters.

**Comment by ShammyLevva** [comment] 2018-12-09 14:37
Hmm interesting so perhaps the key fix here is to look for BOM and add one if missing so the current importing routine works with both types. Thoughts?

**Comment by fire-eggs** [comment] 2018-12-09 18:01
I don't think you can "add a BOM" - you'd be modifying the input file. The BOM is optional; a UTF-8 file should be read as UTF-8 even without the BOM. Here, .NET just happens to be changing behavior when a BOM is seen.

The "usual" approach is to read the file as ASCII until the HEAD.CHAR tag is found. If that tag specifies UTF-8 or Unicode or something else, the file _has to be re-opened_ using the appropriate encoding. The existence of the BOM short-circuits this process: it means the file is UTF-8, regardless of what the HEAD.CHAR tag reads.

[Tamura Jones](https://www.tamurajones.net/GEDCOMCharacterEncodings.xhtml) goes into lots of detail.

Myself, I'd suggest always importing as UTF-8. I think ASCII files will import OK if you do. The question would be whether you have users with Unicode, ANSEL, or non-Windows-1252 codepage files who might be impacted.

**Comment by ShammyLevva** [comment] 2018-12-09 19:48
Yes I'm aware of what the GEDCOM says. However I don't believe the issue is anything to do with the GEDCOM tags in the file. I much more strongly suspect that files are being written with a standard HEAD.CHAR field that has got nothing to do with the actual content.

So I think that program (or website) X will always put HEAD.CHAR as UTF-8 for example regardless of what character set is used. Many don't even have a HEAD.CHAR value.

I had loads of issues with reading as UTF-8 simply not understanding a lot of special characters this was all largely resolved using 1252 character set and ignoring the HEAD.CHAR setting. 

Changing default to UTF-8 from 1252 works for arabic fails for hebrew and fails for french. There's a hideous combo of the HEAD.CHAR settings and file encoding going on here. 

I'm wondering if there's some way to test if the import failed to translate the characters. At present I feel I'm going round in circles.

**Comment by ShammyLevva** [comment] 2018-12-09 19:51
I've sent George a PM on facebook asking for his sample file then I think I'll build a series of test cases to load sample data with different variants of encodings and HEAD.CHAR settings and add a function to measure success. 

Once there's a series of test cases it's easier to tweak things and see what works and what doesn't with various settings. At present I'll commit what I've got and build some tests.

**Comment by ShammyLevva** [comment] 2018-12-09 20:40
Right thanks for the file. Fairly sure I've got a fix which I'll release as v7.0.4.0 soon. I'll leave this open meantime. It seems to fix the Arabic and French imports. Note Excel imports need to use import routine in Excel not just double clicking (this is an Excel issue as fire-eggs pointed out). 

The Hebrew file is still being annoying though so more work to do.

**Comment by fire-eggs** [comment] 2018-12-09 22:50
My mistake then - I thought Win-1252 and UTF-8 would be interchangeable for ASCII. Seems I have some more research to do ...

**Comment by ShammyLevva** [comment] 2018-12-15 00:43
This does seem to be ok now. Can reopen if something else arises.

**Comment by amerkasem85** [comment] 2018-12-15 18:13
I 'm sorry
i was not availabe
in the last version it seems not working also
Sample
https://www.mediafire.com/file/ufkcaocg8dzdr70/Desktop.zip/file

![1](https://user-images.githubusercontent.com/45685601/50046071-41d07200-00ae-11e9-9cea-c65e4137cf2d.jpg)
![2](https://user-images.githubusercontent.com/45685601/50046073-4563f900-00ae-11e9-95e5-f2f1c068ffb9.jpg)

**Comment by ShammyLevva** [comment] 2018-12-16 22:09
Ok I've had another look and found the issue

**Comment by ShammyLevva** [comment] 2018-12-16 22:10
![image](https://user-images.githubusercontent.com/29687786/50059488-5c265080-017f-11e9-93fc-c6b80d351577.png)

**Comment by amerkasem85** [comment] 2018-12-21 12:30
It works now 
Exported Arabic CSV file is ok
Thanx

**Comment by ShammyLevva** [comment] 2018-12-21 14:21
Great I'll close the issue.

**Closed by ShammyLevva** 2018-12-21 14:21 UTC
