### ISSUE TITLE
LC Facts Recorded Display error??

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#183] opened 2020-08-27 13:48 UTC
Re-Opening Bug #126.

V8.0.0.0

I have just run the latest version and on going to the LostCousins tab I have the same problem first exhibited in Bug #126. Seems to be something to do with the 1881 Scotland Census.
![FTA8000 LostCousins ScreenCap](https://user-images.githubusercontent.com/35932839/91450520-4afa7600-e874-11ea-8146-78666b388ccc.JPG)

**Comment by ShammyLevva** [comment] 2020-08-27 14:28
Looking back at bug 126. My last comment was for some more information on what exactly was wrong. you have 1368 bad/missing census facts but I'm not sure what is bad or missing about them nor why that is wrong. Can you give some concrete examples please.

**Comment by Onceageordie** [comment] 2020-08-27 15:06
The whole point, if I remember correctly, is that there IS nothing bad or missing about them. Prior to the version on #126 they were all okay. 

The number of errors compared to the number of Scotland 1881 Census entries seems conspicuous.

If you want, I can export a family from the 1881 Scotland census that appear in the error listing.

**Comment by ShammyLevva** [comment] 2020-08-27 16:41
Thanks I think that will be very useful. I suspect it's how it's identifying the census references that's the root cause.

**Comment by Onceageordie** [comment] 2020-08-27 17:08
If you look at John Paterson (1836) & John Paterson (1879) these are 2 examples where they already exist on LostCousins and both have LostCousins facts. They are already there, but show up in the (big) list. Census references appear correct in Ancestry (and FTM).

**Comment by Onceageordie** [comment] 2020-08-27 17:09
If you look at John Paterson (1836) & John Paterson (1879) these are 2 examples where they already exist on LostCousins and both have LostCousins facts. They are already there, but show up in the (big) list.

I've sent the .ged by email cos it won't accept it here.

**Comment by ShammyLevva** [comment] 2020-09-04 14:06
Hi there can you confirm you emailed ftanalyzer@gmail.com as can't see any attachment come through.

**Comment by ShammyLevva** [comment] 2020-09-05 12:03
Ok the problem was with Margaret Ann Dougal, it erroneously recognised her Lost Cousins fact as both England and Wales 1881 AND Scotland 1881 entry but of course her census record was only Scotland. So it thought there was a missing record.

**Comment by ShammyLevva** [comment] 2020-09-06 12:07
Should now be fixed in v8.0.1

**Closed by ShammyLevva** 2020-09-06 12:07 UTC

**Comment by Onceageordie** [comment] 2020-09-06 12:19
Excellent, many thanks.

 

Dale
