### ISSUE TITLE
Support evidence explained style citations for 1880 census in Lost Cousins upload

### ISSUE THREAD

**Issue by Ann1k3n** [ShammyLevva/FTAnalyzer#240] opened 2021-09-21 21:42 UTC
**Is your feature request related to a problem? Please describe.**
I use evidence explained style citations. My 1940 US census citations are recognized as valid on the Lost Cousins tab, but my 1880 US census citations are considered invalid census references. This means I have a lot of yellow boxes on my color census report.

**Describe the solution you'd like**
I'd like the Lost Cousins tab to consider my 1880 census references as valid, potential uploads.

**Describe alternatives you've considered**
I have considered altering my citation style, but that would be a lot of work for me. I know Ancestry and FamilySearch style citations for the 1880 census are considered valid.

**Additional context**
Here's a sample of an 1880 US census citation in case that helps.
1880 U.S. Census, Montgomery County, Illinois, population schedule, Harvel Township, enumeration district (ED) 149, p. 286B, dwelling 214, family 216, Joseph Sclarman household; digital images, Ancestry (https://www.ancestry.com : accessed 6 June 2020); citing NARA microfilm publication T9, roll 237.

**Comment by ShammyLevva** [comment] 2021-09-22 02:32
This should be relatively easy to add. Can you upload a sample GEDCOM snippet of a single individual with that style of citation so I can see exactly how the GEDCOM is formatted. As the style looks identical to existing patterns but something is obviously different enough that it’s not getting picked up. 

On the census tab there’s a unrecognised census references report. That report would pickup any other formats of note in your file. 

The GEDCOM snippet is however the best source as it may be the formatting is slightly odd and something is getting missed. If for privacy reasons you prefer then you can email the snippet to ftanalyzer@gmail.com.

**Comment by Ann1k3n** [comment] 2021-09-24 00:06
[1880 Census Test.ged.txt](https://github.com/ShammyLevva/FTAnalyzer/files/7221349/1880.Census.Test.ged.txt)
Here's a sample person who has a census citation for 1880 that is considered an invalid census ref for the Lost Cousins upload.

**Comment by ShammyLevva** [comment] 2022-01-03 14:38
Can you clairify what the issue is please the example did not demonstrate the issue.

**Comment by ShammyLevva** [comment] 2022-02-12 17:46
Hi there, is this still an issue if I don't hear back I'll assume all is ok and close the case.

**Comment by ShammyLevva** [comment] 2023-04-23 22:54
The file supplied did not show the issue so I'm assuming this was fixed in one of the earlier census reference updates.

**Closed by ShammyLevva** 2023-04-23 22:54 UTC
Labels: bug, Awaiting User Feedback
