### ISSUE TITLE
Will not even open file

### ISSUE THREAD

**Issue by Chickydu** [ShammyLevva/FTAnalyzer#203] opened 2021-02-06 19:52 UTC
I open FTA, then go to File, open GEDCOM file.  FTA will open file explorer but before I can select a file FTA closes.  I have used FTA for years, and I currently have been loading and working with gedcoms almost daily.

Since the issue, I have run updates on PC and have rebooted several times.  I have gone into my setting, apps, then advance and have run a repair, and reset several times.  I have uninstalled and reinstalled it.  Same issue every time.

Thank you,
Cristina

**Comment by ShammyLevva** [comment] 2021-02-08 01:06
I’d need to know what version you are running and on what version of Windows.

**Comment by Chickydu** [comment] 2021-02-08 16:47
FTAVersion 8.1.2.0App 25.8 MBData 84.0 KBTotal Usage 25.9 MB
Windows 10 HomeVersion 20H2OS build 19042.789Experience Windows Feature Experience Pack 120.2212.551.0

Cristina Denton


-----Original Message-----

**Comment by ShammyLevva** [comment] 2021-02-09 01:01
Ok there is no reason it should crash with a modern version of Windows and new version of FTAnalyzer. 

Since over 1500 people have used this version on Windows and no-one else has reported an issue I assume there is something else at play here. I'd need to see some sort of diagnostic data or a screenshot of the actual problem to help further.

A couple of things you can try though. Run a command prompt by right clicking start button using search option and entering CMD This will find the Microsoft Command prompt app - select the option to run as administrator.

You should then get a black background window open with the title Administrator command prompt.

at the prompt which should normally say 

c:\windows\system32>

enter the following command

sfc /scannow

this is the System File Check (SFC) command that tells windows to scan for any system file errors and repair them. If it finds errors reboot the machine to fix them and then retry the program. If that doesn't make a different then I need an error log to find out why your machine is having a problem and thousands of other people are not. There is another microsoft command to do a more through check of the machine but it takes a while to run. 

Note uninstalling reinstalling will be unlikely to ever fix a problem, yet it is the first thing people try. You need to diagnose the root cause not just reinstall. To diagnose the problem we need actual error messages, and PRECISE steps to reproduce the error.

If it's simply closing when a file explorer window is opening then that is likely to be a File Explorer issue and not an FTAnalyzer issue, so the fix is to do a system file check. What other programs have you tried opening files in to check what File Explorer does for them?

Note I need more info on EXACTLY how FTAnalyzer closes what EXACTLY happens, when EXACTLY does it happen? On clicking a file? On clicking open to open the file? When it closes the file explorer window? What EXACTLY happens? Does it come up with an error window? What does the windows event log say?

At present I'm entirely in the dark as to EXACTLY what is happening so without information I am really struggling to assist.

**Comment by Chickydu** [comment] 2021-02-09 05:08
Other programs do not have an issue opening folders or files.
I have run the sfc /scannow and no errors found.
I don't get any error message when this happens.  I have been using FTA for at least several years, and I use it often and have never had an issue.  I am not blaming FTA, I am just trying to fix my issue and really appreciate all of your help.  I thought I did send you some screenshots?  Here is a video.
Can I use the F word?  LOL    It says my video is too big and won't send

Cristina Denton


-----Original Message-----

**Comment by ShammyLevva** [comment] 2021-02-09 13:13
It maybe that this website won't allow them - you can email me at ftanalyzer.com

I've released a new version v8.2.0.0 with more debugging code turned on to hopefully help diagnose where the issue is. Your Microsoft store should auto update to this.

**Comment by ShammyLevva** [comment] 2021-02-11 17:33
Version 8.3 released hopefully that fixes it.

**Comment by ShammyLevva** [comment] 2021-02-12 18:11
If you still have issues in v8.3.0 you can send video to ftanalyzer@gmail.com

**Comment by ShammyLevva** [comment] 2021-03-02 19:20
No further feedback.

**Closed by ShammyLevva** 2021-03-02 19:20 UTC
