### ISSUE TITLE
View UK colour Census Report _ fails to correctly identify already found Census #213

### ISSUE THREAD

**Issue by jamesWilliamEdwards** [ShammyLevva/FTAnalyzer#213] opened 2021-03-14 17:25 UTC
When using the Research Suggestion tab, view UK Colour Census Report function, the report indicates almost all of the individuals have no census linked to them. This is incorrect, some actually have all of them. I have checked using individuals who I know to have all the records. This issue is a recent occurrence.

I have re-installed the software - version 8 .3.0.0 and the problem continues.

My Gedcom file is generated by FindMyPast.

**Comment by ShammyLevva** [comment] 2021-03-15 22:31
Can you supply a small GEDCOM file with a couple of individuals that demonstrates the issue. ie: export a couple of individuals try that in FTAnalyzer to check the problem exists then send that file to ftanalyzer@gmail.com with the steps required to reproduce the issue.

**Comment by jamesWilliamEdwards** [comment] 2021-03-15 22:46
Hi there, I have already sent a file. If you would prefer I can send you
another.

Regards James

**Comment by ShammyLevva** [comment] 2021-03-15 22:51
I've just seen that file. Unfortunately it's 5Mb in size so not a small snippet of the problem. What I need is a couple of people that have the issue. That is because when I load the file I often need to step through the code line by line for each person it processes. If there are thousands of individuals in the file that becomes an impossible task.  So ideally I need a file of as small a number of people as possible that still demonstrates the issue. 

In addition to the file I need the steps you take to replicate the issue so I can step through the file doing what you did and seeing the issue on my machine. I can then set appropriate "breakpoints" in the code to attempt to diagnose what the code is doing and where it is going wrong.

**Comment by jamesWilliamEdwards** [comment] 2021-03-15 22:58
Not a problem, I will send a smaller one tomorrow if that's OK.

Thank you for your help.
James

**Comment by ShammyLevva** [comment] 2021-03-16 00:23
Sure I’ll have a look at it soon, might not be tomorrow as I’ve a friends thing online in evening after work.

**Comment by jamesWilliamEdwards** [comment] 2021-03-16 07:28
Of course, sorry, I wasn’t suggesting you should/ would have it done. I appreciate you’re a  volunteer.

Thanks
James

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jamesWilliamEdwards** [comment] 2021-03-16 18:01
Hello,

Please find attached a file as requested.

Using Find My Past I have recreated a section of my  tree by adding the census records for Christopher. I have only added the census records to Christopher’s profile, the other persons have been generated using the census data and generated via Christopher’s profile . I have not added any other sources.

To Christopher’s profile I have added census records for 1871, 81, 91, 1901,  1911 and 1939. Therefore if my understanding is correct, none of those dates should be red and because the other individuals have been added using the same census data their corresponding squares should not be red.


***@***.***D71A8E.63E529C0]


Please let me know if I can be of anymore help.

Thanks

James

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ShammyLevva** [comment] 2021-03-16 20:05
Unfortunately GitHub strips attachments if you reply to this announcement. You'd need to email me at ftanalyzer@gmail.com again.

**Comment by ShammyLevva** [comment] 2021-03-16 21:30
New smaller file shows the following : 
![image](https://user-images.githubusercontent.com/29687786/111382355-c996f380-869e-11eb-9ac4-2061e1fc2074.png)
Christopher still looks fine.

**Comment by ShammyLevva** [comment] 2021-03-16 21:44
Fixed in v8.3.1.

**Closed by ShammyLevva** 2021-03-16 21:44 UTC
Labels: bug

**Comment by jamesWilliamEdwards** [comment] 2021-03-16 21:58
As requested I turned on  the option in General Settings to include alternate facts. The following error message appeared;

***@***.***D71AAF.7E165230]

Details Read;

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Font.GetHeight(Graphics graphics)
   at System.Drawing.Font.GetHeight()
   at System.Drawing.Font.get_Height()
   at System.Windows.Forms.GroupBoxRenderer.DrawThemedGroupBoxWithText(Graphics g, Rectangle bounds, String groupBoxText, Font font, Color textColor, TextFormatFlags flags, GroupBoxState state)
   at System.Windows.Forms.GroupBoxRenderer.DrawGroupBox(Graphics g, Rectangle bounds, String groupBoxText, Font font, TextFormatFlags flags, GroupBoxState state)
   at System.Windows.Forms.GroupBox.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.GroupBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FTAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/FTAnalyzer.exe
----------------------------------------
SharpMap
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/SharpMap.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NetTopologySuite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/NetTopologySuite.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
ProjNET
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/ProjNET.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    Assembly Version: 2.0.12.0
    Win32 Version: 2.0.12.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/System.Memory.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.113.0
    Win32 Version: 1.0.113.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/Newtonsoft.Json.DLL
----------------------------------------
Printing.DataGridViewPrint
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/Printing.DataGridViewPrint.DLL
----------------------------------------
GoogleAnalyticsTracker.Core
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/GoogleAnalyticsTracker.Core.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GoogleAnalyticsTracker.Simple
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/26245AlexanderBisset.56195460DD6F1_8.3.0.0_x64__zhq5m3qz969ym/VFS/ProgramFilesX64/FTAnalyzer/FTAnalyzer/GoogleAnalyticsTracker.Simple.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


The Research Suggestions – View UK colour Census Report  now appears as follows (despite the above error) – this appears to match yours. I have crosschecked this with the reference file and it appears to now shows the census records correctly.

***@***.***D71AAF.7E165230]


Thank you for such a swift response, thank you .

James



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
